class QuizQuestion {
  final String question;
  final String option1;
  final String option2;
  final String option3;
  final String option4;
  final String answer;


  QuizQuestion({
    required this.question,
    required this.option1,
    required this.option2,
    required this.option3,
    required this.option4,
    required this.answer,

  });
}


List<QuizQuestion> quizQuestions = [
  QuizQuestion(
    question: "What country has the highest life expectancy?",
    option1: "Japan",
    option2: "Switzerland",
    option3: "Hong Kong",
    option4: "Singapore",
    answer: "Hong Kong",
  ),
  QuizQuestion(
    question: "Where would you be if you were standing on the Spanish Steps?",
    option1: "Madrid",
    option2: "Barcelona",
    option3: "Rome",
    option4: "Paris",
    answer: "Rome",
  ),
  QuizQuestion(
    question: "Which language has the more native speakers: English or Spanish?",
    option1: "English",
    option2: "Spanish",
    option3: "French",
    option4: "Mandarin",
    answer: "Spanish",
  ),
  QuizQuestion(
    question: "What is the most common surname in the United States?",
    option1: "Johnson",
    option2: "Williams",
    option3: "Smith",
    option4: "Jones",
    answer: "Smith",
  ),
  QuizQuestion(
    question: "What disease commonly spread on pirate ships?",
    option1: "Scurvy",
    option2: "Typhus",
    option3: "Tuberculosis",
    option4: "Malaria",
    answer: "Scurvy",
  ),
  QuizQuestion(
    question: "Who was the Ancient Greek God of the Sun?",
    option1: "Hermes",
    option2: "Apollo",
    option3: "Zeus",
    option4: "Ares",
    answer: "Apollo",
  ),
  QuizQuestion(
    question: "What was the name of the crime boss who was head of the feared Chicago Outfit?",
    option1: "John Dillinger",
    option2: "Al Capone",
    option3: "Lucky Luciano",
    option4: "Bugsy Siegel",
    answer: "Al Capone",
  ),
  QuizQuestion(
    question: "What year was the United Nations established?",
    option1: "1939",
    option2: "1940",
    option3: "1945",
    option4: "1950",
    answer: "1945",
  ),
  QuizQuestion(
    question: "Who has won the most total Academy Awards?",
    option1: "Walt Disney",
    option2: "Steven Spielberg",
    option3: "Katharine Hepburn",
    option4: "Meryl Streep",
    answer: "Walt Disney",
  ),
  QuizQuestion(
    question: "What artist has the most streams on Spotify?",
    option1: "Ed Sheeran",
    option2: "Ariana Grande",
    option3: "Drake",
    option4: "The Weeknd",
    answer: "Drake",
  ),
  QuizQuestion(
    question: "How many minutes are in a full week?",
    option1: "7,200",
    option2: "10,080",
    option3: "14,400",
    option4: "20,160",
    answer: "10,080",
  ),
  QuizQuestion(
    question: "What car manufacturer had the highest revenue in 2020?",
    option1: "Toyota",
    option2: "General Motors",
    option3: "Ford",
    option4: "Volkswagen",
    answer: "Volkswagen",
  ),
  QuizQuestion(
    question: "How many elements are in the periodic table?",
    option1: "108",
    option2: "114",
    option3: "118",
    option4: "120",
    answer: "118",
  ),
  QuizQuestion(
    question: "What company was originally called 'Cadabra'?",
    option1: "eBay",
    option2: "Google",
    option3: "Amazon",
    option4: "Microsoft",
    answer: "Amazon",
  ),
  QuizQuestion(
    question: "How many faces does a Dodecahedron have?",
    option1: "6",
    option2: "8",
    option3: "12",
    option4: "20",
    answer: "12",
  ),
  QuizQuestion(
    question: "Queen guitarist Brian May is also an expert in what scientific field?",
    option1: "Chemistry",
    option2: "Astrophysics",
    option3: "Biology",
    option4: "Physics",
    answer: "Astrophysics",
  ),
  QuizQuestion(
    question: "Aureolin is a shade of what color?",
    option1: "Blue",
    option2: "Green",
    option3: "Yellow",
    option4: "Red",
    answer: "Yellow",
  ),
  QuizQuestion(
    question: "How many ghosts chase Pac-Man at the start of each game?",
    option1: "2",
    option2: "3",
    option3: "4",
    option4: "5",
    answer: "4",
  ),
  QuizQuestion(
    question: "What Renaissance artist is buried in Rome's Pantheon?",
    option1: "Leonardo da Vinci",
    option2: "Michelangelo",
    option3: "Raphael",
    option4: "Donatello",
    answer: "Raphael",
  ),
  QuizQuestion(
    question: "What shoe brand makes the 'Mexico 66'?",
    option1: "Nike",
    option2: "Adidas",
    option3: "Puma",
    option4: "Onitsuka Tiger",
    answer: "Onitsuka Tiger",
  ),
  QuizQuestion(
    question: "What game studio makes the Red Dead Redemption series?",
    option1: "Bethesda",
    option2: "Electronic Arts",
    option3: "Rockstar Games",
    option4: "Ubisoft",
    answer: "Rockstar Games",
  ),
  QuizQuestion(
    question: "Who was the last Tsar of Russia?",
    option1: "Nicholas I",
    option2: "Nicholas II",
    option3: "Alexander III",
    option4: "Peter the Great",
    answer: "Nicholas II",
  ),
  QuizQuestion(
    question: "What character have both Robert Downey Jr. and Benedict Cumberbatch played?",
    option1: "Iron Man",
    option2: "Sherlock Holmes",
    option3: "Doctor Strange",
    option4: "Captain America",
    answer: "Sherlock Holmes",
  ),
  QuizQuestion(
    question: "What country drinks the most coffee per capita?",
    option1: "Brazil",
    option2: "Finland",
    option3: "Colombia",
    option4: "Italy",
    answer: "Finland",
  ),
  QuizQuestion(
    question: "Which planet in the Milky Way is the hottest?",
    option1: "Mars",
    option2: "Mercury",
    option3: "Venus",
    option4: "Jupiter",
    answer: "Venus",
  ),
  QuizQuestion(
    question: "What is the 4th letter of the Greek alphabet?",
    option1: "Alpha",
    option2: "Beta",
    option3: "Gamma",
    option4: "Delta",
    answer: "Delta",
  ),
  QuizQuestion(
    question: "What sports car company manufactures the 911?",
    option1: "Ferrari",
    option2: "Lamborghini",
    option3: "Porsche",
    option4: "Maserati",
    answer: "Porsche",
  ),
  QuizQuestion(
    question: "What city is known as 'The Eternal City'?",
    option1: "Athens",
    option2: "Rome",
    option3: "Paris",
    option4: "Jerusalem",
    answer: "Rome",
  ),
  QuizQuestion(
    question: "Roald Amundsen was the first man to reach the South Pole, but where was he from?",
    option1: "Sweden",
    option2: "Denmark",
    option3: "Norway",
    option4: "Finland",
    answer: "Norway",
  ),
  QuizQuestion(
    question: "What is the highest-rated film on IMDb as of January 1st, 2022?",
    option1: "The Godfather",
    option2: "The Shawshank Redemption",
    option3: "The Dark Knight",
    option4: "Forrest Gump",
    answer: "The Shawshank Redemption",
  ),
  QuizQuestion(
    question: "Who discovered that the earth revolves around the sun?",
    option1: "Galileo Galilei",
    option2: "Isaac Newton",
    option3: "Nicolaus Copernicus",
    option4: "Johannes Kepler",
    answer: "Nicolaus Copernicus",
  ),
  QuizQuestion(
    question: "What company was initially known as 'Blue Ribbon Sports'?",
    option1: "Nike",
    option2: "Adidas",
    option3: "Puma",
    option4: "Reebok",
    answer: "Nike",
  ),
  QuizQuestion(
    question: "What art form is described as 'decorative handwriting or handwritten lettering'?",
    option1: "Typography",
    option2: "Calligraphy",
    option3: "Printmaking",
    option4: "Illumination",
    answer: "Calligraphy",
  ),
   QuizQuestion(
    question: "Which planet has the most moons?",
    option1: "Jupiter",
    option2: "Saturn",
    option3: "Uranus",
    option4: "Neptune",
    answer: "Saturn",
  ),
  QuizQuestion(
    question: "What country has won the most World Cups?",
    option1: "Germany",
    option2: "Argentina",
    option3: "Brazil",
    option4: "Italy",
    answer: "Brazil",
  ),
  QuizQuestion(
    question: "Complete the following lyrics - 'I should have changed that stupid lock.....'",
    option1: "I should have made you leave your key",
    option2: "I should have told you what I think",
    option3: "I should have stayed and made you stay",
    option4: "I should have turned off my phone",
    answer: "I should have made you leave your key",
  ),
  QuizQuestion(
    question: "Kratos is the main character of what video game series?",
    option1: "God of War",
    option2: "Assassin's Creed",
    option3: "The Last of Us",
    option4: "Dark Souls",
    answer: "God of War",
  ),
  QuizQuestion(
    question: "In what country would you find Mount Kilimanjaro?",
    option1: "Kenya",
    option2: "Tanzania",
    option3: "Uganda",
    option4: "Rwanda",
    answer: "Tanzania",
  ),
  QuizQuestion(
    question: "What is a group of pandas known as?",
    option1: "A prickle",
    option2: "A bloat",
    option3: "An embarrassment",
    option4: "A dazzle",
    answer: "An embarrassment",
  ),
  QuizQuestion(
    question: "What European country experienced the highest rate of population decline from 2015 - 2020?",
    option1: "Latvia",
    option2: "Lithuania",
    option3: "Bulgaria",
    option4: "Serbia",
    answer: "Lithuania",
  ),
  QuizQuestion(
    question: "How many bones do we have in an ear?",
    option1: "2",
    option2: "3",
    option3: "4",
    option4: "5",
    answer: "3",
  ),
  QuizQuestion(
    question: "Who famously crossed the Alps with elephants on the way to war with the Romans?",
    option1: "Julius Caesar",
    option2: "Hannibal",
    option3: "Alexander the Great",
    option4: "Attila the Hun",
    answer: "Hannibal",
  ),
  QuizQuestion(
    question: "True or False: Halloween originated as an ancient Irish festival.",
    option1: "True",
    option2: "False",
    option3: "",
    option4: "",
    answer: "True",
  ),
  QuizQuestion(
    question: "What Netflix show had the most streaming views in 2021?",
    option1: "Money Heist",
    option2: "Stranger Things",
    option3: "Bridgerton",
    option4: "Squid Game",
    answer: "Squid Game",
  ),
  QuizQuestion(
    question: "Which Grammy-nominated New York rapper died in April of 2021?",
    option1: "Nas",
    option2: "Jay-Z",
    option3: "DMX",
    option4: "Asap Rocky",
    answer: "DMX",
  ),
  QuizQuestion(
    question: "What software company is headquartered in Redmond, Washington?",
    option1: "Apple",
    option2: "Google",
    option3: "Microsoft",
    option4: "Amazon",
    answer: "Microsoft",
  ),
  QuizQuestion(
    question: "What is the largest Spanish-speaking city in the world?",
    option1: "Buenos Aires",
    option2: "Madrid",
    option3: "Mexico City",
    option4: "Barcelona",
    answer: "Mexico City",
  ),
  QuizQuestion(
    question: "What is the world's fastest bird?",
    option1: "Golden Eagle",
    option2: "Peregrine Falcon",
    option3: "Hawk",
    option4: "Albatross",
    answer: "Peregrine Falcon",
  ),
  QuizQuestion(
    question: "In what country is the Chernobyl nuclear plant located?",
    option1: "Russia",
    option2: "Belarus",
    option3: "Ukraine",
    option4: "Poland",
    answer: "Ukraine",
  ),
  QuizQuestion(
    question: "The Parthenon Marbles are controversially located in what museum?",
    option1: "The Louvre",
    option2: "The British Museum",
    option3: "The Vatican Museums",
    option4: "The Metropolitan Museum of Art",
    answer: "The British Museum",
  ),
 QuizQuestion(
    question: "Who wrote the novel '1984'?",
    option1: "George Orwell",
    option2: "J.K. Rowling",
    option3: "F. Scott Fitzgerald",
    option4: "Ernest Hemingway",
    answer: "George Orwell",
  ),
  QuizQuestion(
    question: "What is the capital city of Australia?",
    option1: "Sydney",
    option2: "Melbourne",
    option3: "Canberra",
    option4: "Brisbane",
    answer: "Canberra",
  ),
  QuizQuestion(
    question: "What is the chemical symbol for Gold?",
    option1: "Gd",
    option2: "Go",
    option3: "Ag",
    option4: "Au",
    answer: "Au",
  ),
  QuizQuestion(
    question: "In what year was the first iPhone released?",
    option1: "2005",
    option2: "2007",
    option3: "2008",
    option4: "2010",
    answer: "2007",
  ),
  QuizQuestion(
    question: "What is the tallest mountain in the world?",
    option1: "K2",
    option2: "Mount Everest",
    option3: "Mount Kilimanjaro",
    option4: "Denali",
    answer: "Mount Everest",
  ),
  QuizQuestion(
    question: "Who painted the 'Mona Lisa'?",
    option1: "Leonardo da Vinci",
    option2: "Michelangelo",
    option3: "Raphael",
    option4: "Caravaggio",
    answer: "Leonardo da Vinci",
  ),
  QuizQuestion(
    question: "Which planet is known as the 'Red Planet'?",
    option1: "Venus",
    option2: "Mars",
    option3: "Jupiter",
    option4: "Saturn",
    answer: "Mars",
  ),
  QuizQuestion(
    question: "Who discovered electricity?",
    option1: "Isaac Newton",
    option2: "Nikola Tesla",
    option3: "Michael Faraday",
    option4: "Benjamin Franklin",
    answer: "Benjamin Franklin",
  ),
  QuizQuestion(
    question: "What is the world's largest ocean?",
    option1: "Atlantic Ocean",
    option2: "Indian Ocean",
    option3: "Pacific Ocean",
    option4: "Southern Ocean",
    answer: "Pacific Ocean",
  ),
  QuizQuestion(
    question: "Who came up with the theory of relativity?",
    option1: "Edgar Allan Poe",
    option2: "Albert Einstein",
    option3: "Galileo Galilei",
    option4: "Louis Pasteur",
    answer: "Albert Einstein",
  ),
  QuizQuestion(
    question: "What is the national bird of the United States?",
    option1: "Eagle",
    option2: "Bald Eagle",
    option3: "Condor",
    option4: "Pigeon",
    answer: "Bald Eagle",
  ),
  QuizQuestion(
    question: "What language is spoken in Brazil?",
    option1: "Spanish",
    option2: "Portuguese",
    option3: "English",
    option4: "French",
    answer: "Portuguese",
  ),
  QuizQuestion(
    question: "Who directed the movie 'Jurassic Park'?",
    option1: "Steven Spielberg",
    option2: "George Lucas",
    option3: "Michael Bay",
    option4: "Stanley Kubrick",
    answer: "Steven Spielberg",
  ),
  QuizQuestion(
    question: "What is sushi traditionally wrapped in?",
    option1: "Rice Paper",
    option2: "Seaweed",
    option3: "Bamboo",
    option4: "Lettuce",
    answer: "Seaweed",
  ),
  QuizQuestion(
    question: "What is the main ingredient in hummus?",
    option1: "Potatoes",
    option2: "Lentils",
    option3: "Chickpeas",
    option4: "White Beans",
    answer: "Chickpeas",
  ),
  QuizQuestion(
    question: "Who is the author of the 'Harry Potter' series?",
    option1: "J.D. Salinger",
    option2: "Roald Dahl",
    option3: "Suzanne Collins",
    option4: "J.K. Rowling",
    answer: "J.K. Rowling",
  ),
  QuizQuestion(
    question: "How many players are there in a soccer team?",
    option1: "6",
    option2: "11",
    option3: "9",
    option4: "4",
    answer: "11",
  ),
  QuizQuestion(
    question: "What does a barometer measure?",
    option1: "Sound",
    option2: "Light",
    option3: "Atmospheric Pressure",
    option4: "Humidity",
    answer: "Atmospheric Pressure",
  ),
  QuizQuestion(
    question: "What is the highest-grossing film of all time?",
    option1: "Titanic",
    option2: "Avatar",
    option3: "Avengers: Endgame",
    option4: "Star Wars: The Force Awakens",
    answer: "Avengers: Endgame",
  ),
  QuizQuestion(
    question: "In what decade was the Internet created?",
    option1: "1960s",
    option2: "1970s",
    option3: "1980s",
    option4: "1990s",
    answer: "1960s",
  ),
  QuizQuestion(
    question: "How many teeth does an adult human have?",
    option1: "28",
    option2: "32",
    option3: "30",
    option4: "26",
    answer: "32",
  ),
  QuizQuestion(
    question: "Who invented the lightbulb?",
    option1: "Albert Einstein",
    option2: "Nikola Tesla",
    option3: "Thomas Edison",
    option4: "Alexander Graham Bell",
    answer: "Thomas Edison",
  ),
  QuizQuestion(
    question: "What is the hottest planet in the solar system?",
    option1: "Mercury",
    option2: "Mars",
    option3: "Venus",
    option4: "Jupiter",
    answer: "Venus",
  ),
  QuizQuestion(
    question: "Who composed the music for 'The Nutcracker'?",
    option1: "Mozart",
    option2: "Beethoven",
    option3: "Tchaikovsky",
    option4: "Bach",
    answer: "Tchaikovsky",
  ),
  QuizQuestion(
    question: "What does NASA stand for?",
    option1: "North American Satellite Association",
    option2: "National Aeronautics and Space Administration",
    option3: "National Association of Space Astronauts",
    option4: "National American Space Association",
    answer: "National Aeronautics and Space Administration",
  ),
  QuizQuestion(
    question: "Who was the first President of the United States?",
    option1: "Thomas Jefferson",
    option2: "Benjamin Franklin",
    option3: "Abraham Lincoln",
    option4: "George Washington",
    answer: "George Washington",
  ),
  QuizQuestion(
    question: "In what year was the United Nations founded?",
    option1: "1920",
    option2: "1945",
    option3: "1950",
    option4: "1935",
    answer: "1945",
  ),
  QuizQuestion(
    question: "Who is the CEO of Tesla?",
    option1: "Jeff Bezos",
    option2: "Mark Zuckerberg",
    option3: "Tim Cook",
    option4: "Elon Musk",
    answer: "Elon Musk",
  ),
  QuizQuestion(
    question: "What type of animal is a penguin?",
    option1: "Mammal",
    option2: "Reptile",
    option3: "Insect",
    option4: "Bird",
    answer: "Bird",
  ),
  QuizQuestion(
    question: "What is the capital city of Canada?",
    option1: "Vancouver",
    option2: "Toronto",
    option3: "Quebec City",
    option4: "Ottawa",
    answer: "Ottawa",
  ),
  QuizQuestion(
    question: "What is the strongest muscle in the human body?",
    option1: "Biceps",
    option2: "Quadriceps",
    option3: "Heart",
    option4: "Jaw Muscle (Masseter)",
    answer: "Jaw Muscle (Masseter)",
  ),
  QuizQuestion(
    question: "Who wrote the novel 'Pride and Prejudice'?",
    option1: "Charlotte Bronte",
    option2: "Mary Shelley",
    option3: "Jane Austen",
    option4: "Emily Dickinson",
    answer: "Jane Austen",
  ),
  QuizQuestion(
    question: "What is the fastest land animal?",
    option1: "Cheetah",
    option2: "Ostrich",
    option3: "Lion",
    option4: "Elephant",
    answer: "Cheetah",
  ),
QuizQuestion(
      question: 'Who painted "Starry Night"?',
      option1: 'Pablo Picasso',
      option2: 'Vincent van Gogh',
      option3: 'Claude Monet',
      option4: 'Edvard Munch',
      answer: 'Vincent van Gogh',
    ),
    QuizQuestion(
      question: 'How many bones are there in the adult human body?',
      option1: '256',
      option2: '206',
      option3: '216',
      option4: '232',
      answer: '206',
    ),
    QuizQuestion(
      question: 'What is the largest country in the world by area?',
      option1: 'Canada',
      option2: 'United States',
      option3: 'Australia',
      option4: 'Russia',
      answer: 'Russia',
    ),
    QuizQuestion(
      question: 'What is the loudest animal on Earth?',
      option1: 'Lion',
      option2: 'Elephant',
      option3: 'Blue Whale',
      option4: 'Sperm Whale',
      answer: 'Sperm Whale',
    ),
    QuizQuestion(
      question: 'What is the smallest country in the world?',
      option1: 'Monaco',
      option2: 'Vatican City',
      option3: 'Malta',
      option4: 'San Marino',
      answer: 'Vatican City',
    ),
    QuizQuestion(
      question: 'Who was Shakespeare?',
      option1: 'A classical composer',
      option2: 'A British King',
      option3: 'An English playwright and poet',
      option4: 'A scientist',
      answer: 'An English playwright and poet',
    ),
    QuizQuestion(
      question: 'Who discovered penicillin?',
      option1: 'Isaac Newton',
      option2: 'Thomas Edison',
      option3: 'Marie Curie',
      option4: 'Alexander Fleming',
      answer: 'Alexander Fleming',
    ),
    QuizQuestion(
      question: 'What are the primary colors?',
      option1: 'Yellow, Blue, Red',
      option2: 'Yellow, Orange, Green',
      option3: 'Orange, Purple, Green',
      option4: 'Blue, Green, Yellow',
      answer: 'Yellow, Blue, Red',
    ),
    QuizQuestion(
      question: 'What does WWW stand for?',
      option1: 'World Wide Web',
      option2: 'World Web Warriors',
      option3: 'Wide World Web',
      option4: 'Web Wide World',
      answer: 'World Wide Web',
    ),
    QuizQuestion(
      question: 'What is the capital city of Spain?',
      option1: 'Seville',
      option2: 'Barcelona',
      option3: 'Valencia',
      option4: 'Madrid',
      answer: 'Madrid',
    ),
    QuizQuestion(
      question: 'Who directed the movie "Titanic"?',
      option1: 'Steven Spielberg',
      option2: 'James Cameron',
      option3: 'Alfred Hitchcock',
      option4: 'Tim Burton',
      answer: 'James Cameron',
    ),
    QuizQuestion(
      question: 'In what year was Facebook founded?',
      option1: '2000',
      option2: '2004',
      option3: '2008',
      option4: '2010',
      answer: '2004',
    ),
    QuizQuestion(
      question: 'Who were the Wright Brothers?',
      option1: 'Scientists who discovered electricity',
      option2: 'Astronauts who landed on the moon',
      option3: 'Soviet spies during the cold war',
      option4: 'Pioneers in aviation',
      answer: 'Pioneers in aviation',
    ),
    QuizQuestion(
      question: 'What is the square root of 121?',
      option1: '10',
      option2: '13',
      option3: '11',
      option4: '9',
      answer: '11',
    ),
    QuizQuestion(
      question: 'Who was the first man to walk on the moon?',
      option1: 'John Glenn',
      option2: 'Yuri Gagarin',
      option3: 'Buzz Aldrin',
      option4: 'Neil Armstrong',
      answer: 'Neil Armstrong',
    ),
    QuizQuestion(
      question: 'What is the world\'s largest desert?',
      option1: 'Mojave',
      option2: 'Siberian Desert',
      option3: 'Sahara',
      option4: 'Antarctic Desert',
      answer: 'Antarctic Desert',
    ),
    QuizQuestion(
      question: 'Who composed the Four Seasons?',
      option1: 'Beethoven',
      option2: 'Mozart',
      option3: 'Vivaldi',
      option4: 'Handel',
      answer: 'Vivaldi',
    ),
    QuizQuestion(
      question: 'How many strings does a standard guitar have?',
      option1: 'Four',
      option2: 'Five',
      option3: 'Six',
      option4: 'Seven',
      answer: 'Six',
    ),
    QuizQuestion(
      question: 'What is the capital city of Italy?',
      option1: 'Milan',
      option2: 'Venice',
      option3: 'Florence',
      option4: 'Rome',
      answer: 'Rome',
    ),
    QuizQuestion(
      question: 'Who is the hero of the "Indiana Jones" series?',
      option1: 'Tom Cruise',
      option2: 'Harrison Ford',
      option3: 'Chris Evans',
      option4: 'Robert Downey Jr.',
      answer: 'Harrison Ford',
    ),
    QuizQuestion(
      question: 'What kind of animal is Shrek?',
      option1: 'Donkey',
      option2: 'Dragon',
      option3: 'Ogre',
      option4: 'Giant',
      answer: 'Ogre',
    ),
    QuizQuestion(
      question: 'What is the biggest animal in the world?',
      option1: 'African Elephant',
      option2: 'Blue Whale',
      option3: 'Saltwater Crocodile',
      option4: 'White Rhinoceros',
      answer: 'Blue Whale',
    ),
    QuizQuestion(
      question: 'In what country are the 2024 Summer Olympics held?',
      option1: 'Tokyo, Japan',
      option2: 'Rio de Janeiro, Brazil',
      option3: 'London, United Kingdom',
      option4: 'Paris, France',
      answer: 'Paris, France',
    ),
    QuizQuestion(
      question: 'What language is spoken in Argentina?',
      option1: 'English',
      option2: 'Portuguese',
      option3: 'Spanish',
      option4: 'French',
      answer: 'Spanish',
    ),
    QuizQuestion(
      question: 'Who painted "The Scream"?',
      option1: 'Pablo Picasso',
      option2: 'Vincent van Gogh',
      option3: 'Edvard Munch',
      option4: 'Claude Monet',
      answer: 'Edvard Munch',
    ),
    QuizQuestion(
      question: 'What is the primary gas found in the Earth\'s atmosphere?',
      option1: 'Oxygen',
      option2: 'Argon',
      option3: 'Carbon Dioxide',
      option4: 'Nitrogen',
      answer: 'Nitrogen',
    ),
    QuizQuestion(
      question: 'Who is the author of "The Great Gatsby"?',
      option1: 'J.D. Salinger',
      option2: 'Ernest Hemingway',
      option3: 'F. Scott Fitzgerald',
      option4: 'Mark Twain',
      answer: 'F. Scott Fitzgerald',
    ),
    QuizQuestion(
      question: 'What is the longest river in the world?',
      option1: 'Amazon River',
      option2: 'Nile River',
      option3: 'Yangtze River',
      option4: 'Mississippi River',
      answer: 'Nile River',
    ),
    QuizQuestion(
      question: 'Who are the two main characters in "Romeo and Juliet"?',
      option1: 'Hamlet and Ophelia',
      option2: 'Macbeth and Lady Macbeth',
      option3: 'Romeo and Juliet',
      option4: 'Othello and Desdemona',
      answer: 'Romeo and Juliet',
    ),
QuizQuestion(
      question: 'In what country are the Pyramids of Giza located?',
      option1: 'Saudi Arabia',
      option2: 'Egypt',
      option3: 'Jordan',
      option4: 'Iraq',
      answer: 'Egypt',
    ),
    QuizQuestion(
      question: 'What is the largest planet in our Solar System?',
      option1: 'Earth',
      option2: 'Mars',
      option3: 'Jupiter',
      option4: 'Saturn',
      answer: 'Jupiter',
    ),
    QuizQuestion(
      question: 'Who wrote "To Kill a Mockingbird"?',
      option1: 'Harper Lee',
      option2: 'J.K. Rowling',
      option3: 'George Orwell',
      option4: 'Jane Austen',
      answer: 'Harper Lee',
    ),
    QuizQuestion(
      question: 'What is the chemical symbol for gold?',
      option1: 'Ag',
      option2: 'Au',
      option3: 'Pb',
      option4: 'Fe',
      answer: 'Au',
    ),
    QuizQuestion(
      question: 'Which planet is known as the Red Planet?',
      option1: 'Earth',
      option2: 'Mars',
      option3: 'Venus',
      option4: 'Mercury',
      answer: 'Mars',
    ),
    QuizQuestion(
      question: 'What is the smallest prime number?',
      option1: '0',
      option2: '1',
      option3: '2',
      option4: '3',
      answer: '2',
    ),
    QuizQuestion(
      question: 'Who is known as the "Father of Computers"?',
      option1: 'Charles Babbage',
      option2: 'Alan Turing',
      option3: 'Ada Lovelace',
      option4: 'Bill Gates',
      answer: 'Charles Babbage',
    ),
    QuizQuestion(
      question: 'What is the most common element in the universe?',
      option1: 'Oxygen',
      option2: 'Carbon',
      option3: 'Hydrogen',
      option4: 'Helium',
      answer: 'Hydrogen',
    ),
    QuizQuestion(
      question: 'Which Shakespeare play features the character of Iago?',
      option1: 'Hamlet',
      option2: 'Othello',
      option3: 'Macbeth',
      option4: 'King Lear',
      answer: 'Othello',
    ),
    QuizQuestion(
      question: 'What is the freezing point of water in Celsius?',
      option1: '0',
      option2: '32',
      option3: '100',
      option4: '273',
      answer: '0',
    ),
    QuizQuestion(
      question: 'What is the capital of Australia?',
      option1: 'Sydney',
      option2: 'Melbourne',
      option3: 'Canberra',
      option4: 'Brisbane',
      answer: 'Canberra',
    ),
 QuizQuestion(
      question: 'What is the chemical symbol for Gold?',
      option1: 'Gd',
      option2: 'Go',
      option3: 'Ag',
      option4: 'Au',
      answer: 'Au',
    ),
    QuizQuestion(
      question: 'In what year was the first iPhone released?',
      option1: '2005',
      option2: '2007',
      option3: '2008',
      option4: '2010',
      answer: '2007',
    ),
    QuizQuestion(
      question: 'What is the tallest mountain in the world?',
      option1: 'K2',
      option2: 'Mount Everest',
      option3: 'Mount Kilimanjaro',
      option4: 'Denali',
      answer: 'Mount Everest',
    ),
    QuizQuestion(
      question: 'Who painted the "Mona Lisa"?',
      option1: 'Leonardo da Vinci',
      option2: 'Michelangelo',
      option3: 'Raphael',
      option4: 'Caravaggio',
      answer: 'Leonardo da Vinci',
    ),
    QuizQuestion(
      question: 'Which planet is known as the "Red Planet"?',
      option1: 'Venus',
      option2: 'Mars',
      option3: 'Jupiter',
      option4: 'Saturn',
      answer: 'Mars',
    ),
    QuizQuestion(
      question: 'Who discovered electricity?',
      option1: 'Isaac Newton',
      option2: 'Nikola Tesla',
      option3: 'Michael Faraday',
      option4: 'Benjamin Franklin',
      answer: 'Benjamin Franklin',
    ),
    QuizQuestion(
      question: 'What is the world\'s largest ocean?',
      option1: 'Atlantic Ocean',
      option2: 'Indian Ocean',
      option3: 'Pacific Ocean',
      option4: 'Southern Ocean',
      answer: 'Pacific Ocean',
    ),
    QuizQuestion(
      question: 'Who came up with the theory of relativity?',
      option1: 'Edgar Allan Poe',
      option2: 'Albert Einstein',
      option3: 'Galileo Galilei',
      option4: 'Louis Pasteur',
      answer: 'Albert Einstein',
    ),
    QuizQuestion(
      question: 'What is the national bird of the United States?',
      option1: 'Eagle',
      option2: 'Bald Eagle',
      option3: 'Condor',
      option4: 'Pigeon',
      answer: 'Bald Eagle',
    ),
    QuizQuestion(
      question: 'What language is spoken in Brazil?',
      option1: 'Spanish',
      option2: 'Portuguese',
      option3: 'English',
      option4: 'French',
      answer: 'Portuguese',
    ),
    QuizQuestion(
      question: 'Who directed the movie "Jurassic Park"?',
      option1: 'Steven Spielberg',
      option2: 'George Lucas',
      option3: 'Michael Bay',
      option4: 'Stanley Kubrick',
      answer: 'Steven Spielberg',
    ),
    QuizQuestion(
      question: 'What is sushi traditionally wrapped in?',
      option1: 'Rice Paper',
      option2: 'Seaweed',
      option3: 'Bamboo',
      option4: 'Lettuce',
      answer: 'Seaweed',
    ),
    QuizQuestion(
      question: 'What is the main ingredient in hummus?',
      option1: 'Potatoes',
      option2: 'Lentils',
      option3: 'Chickpeas',
      option4: 'White Beans',
      answer: 'Chickpeas',
    ),
    QuizQuestion(
      question: 'Who is the author of the "Harry Potter" series?',
      option1: 'J.D. Salinger',
      option2: 'Roald Dahl',
      option3: 'Suzanne Collins',
      option4: 'J.K. Rowling',
      answer: 'J.K. Rowling',
    ),
    QuizQuestion(
      question: 'How many players are there in a soccer team?',
      option1: '6',
      option2: '11',
      option3: '9',
      option4: '4',
      answer: '11',
    ),
    QuizQuestion(
      question: 'What does a barometer measure?',
      option1: 'Sound',
      option2: 'Light',
      option3: 'Atmospheric Pressure',
      option4: 'Humidity',
      answer: 'Atmospheric Pressure',
    ),
    QuizQuestion(
      question: 'What is the highest-grossing film of all time?',
      option1: 'Titanic',
      option2: 'Avatar',
      option3: 'Avengers: Endgame',
      option4: 'Star Wars: The Force Awakens',
      answer: 'Avengers: Endgame',
    ),
    QuizQuestion(
      question: 'In what decade was the Internet created?',
      option1: '1960s',
      option2: '1970s',
      option3: '1980s',
      option4: '1990s',
      answer: '1960s',
    ),
    QuizQuestion(
      question: 'How many teeth does an adult human have?',
      option1: '28',
      option2: '32',
      option3: '30',
      option4: '26',
      answer: '32',
    ),
    QuizQuestion(
      question: 'Who invented the lightbulb?',
      option1: 'Albert Einstein',
      option2: 'Nikola Tesla',
      option3: 'Thomas Edison',
      option4: 'Alexander Graham Bell',
      answer: 'Thomas Edison',
    ),
    QuizQuestion(
      question: 'What is the hottest planet in the solar system?',
      option1: 'Mercury',
      option2: 'Mars',
      option3: 'Venus',
      option4: 'Jupiter',
      answer: 'Venus',
    ),
    QuizQuestion(
      question: 'Who composed the music for "The Nutcracker"?',
      option1: 'Mozart',
      option2: 'Beethoven',
      option3: 'Tchaikovsky',
      option4: 'Bach',
      answer: 'Tchaikovsky',
    ),
    QuizQuestion(
      question: 'What does NASA stand for?',
      option1: 'North American Satellite Association',
      option2: 'National Aeronautics and Space Administration',
      option3: 'National Association of Space Astronauts',
      option4: 'National American Space Association',
      answer: 'National Aeronautics and Space Administration',
    ),
    QuizQuestion(
      question: 'Who was the first President of the United States?',
      option1: 'Thomas Jefferson',
      option2: 'Benjamin Franklin',
      option3: 'Abraham Lincoln',
      option4: 'George Washington',
      answer: 'George Washington',
    ),
    QuizQuestion(
      question: 'In what year was the United Nations founded?',
      option1: '1920',
      option2: '1945',
      option3: '1950',
      option4: '1935',
      answer: '1945',
    ),
    QuizQuestion(
      question: 'Who is the CEO of Tesla?',
      option1: 'Jeff Bezos',
      option2: 'Mark Zuckerberg',
      option3: 'Tim Cook',
      option4: 'Elon Musk',
      answer: 'Elon Musk',
    ),
    QuizQuestion(
      question: 'What type of animal is a penguin?',
      option1: 'Mammal',
      option2: 'Reptile',
      option3: 'Insect',
      option4: 'Bird',
      answer: 'Bird',
    ),
    QuizQuestion(
      question: 'What is the capital city of Canada?',
      option1: 'Vancouver',
      option2: 'Toronto',
      option3: 'Quebec City',
      option4: 'Ottawa',
      answer: 'Ottawa',
    ),
    QuizQuestion(
      question: 'What is the strongest muscle in the human body?',
      option1: 'Biceps',
      option2: 'Quadriceps',
      option3: 'Heart',
      option4: 'Jaw Muscle (Masseter)',
      answer: 'Jaw Muscle (Masseter)',
    ),
    QuizQuestion(
      question: 'Who wrote the novel "Pride and Prejudice"?',
      option1: 'Charlotte Bronte',
      option2: 'Mary Shelley',
      option3: 'Jane Austen',
      option4: 'Emily Dickinson',
      answer: 'Jane Austen',
    ),
    QuizQuestion(
      question: 'What is the fastest land animal?',
      option1: 'Cheetah',
      option2: 'Ostrich',
      option3: 'Lion',
      option4: 'Elephant',
      answer: 'Cheetah',
    ),
    QuizQuestion(
      question: 'Who painted "Starry Night"?',
      option1: 'Pablo Picasso',
      option2: 'Vincent van Gogh',
      option3: 'Claude Monet',
      option4: 'Edvard Munch',
      answer: 'Vincent van Gogh',
    ),
    QuizQuestion(
      question: 'How many bones are there in the adult human body?',
      option1: '256',
      option2: '206',
      option3: '216',
      option4: '232',
      answer: '206',
    ),
 QuizQuestion(
      question: 'What is the smallest planet in our solar system?',
      option1: 'Mercury',
      option2: 'Mars',
      option3: 'Venus',
      option4: 'Earth',
      answer: 'Mercury',
    ),
    QuizQuestion(
      question: 'Who wrote "To Kill a Mockingbird"?',
      option1: 'Harper Lee',
      option2: 'Mark Twain',
      option3: 'Ernest Hemingway',
      option4: 'F. Scott Fitzgerald',
      answer: 'Harper Lee',
    ),
    QuizQuestion(
      question: 'Which element has the chemical symbol "O"?',
      option1: 'Gold',
      option2: 'Oxygen',
      option3: 'Osmium',
      option4: 'Oganesson',
      answer: 'Oxygen',
    ),
    QuizQuestion(
      question: 'What is the largest desert in the world?',
      option1: 'Sahara Desert',
      option2: 'Gobi Desert',
      option3: 'Antarctic Desert',
      option4: 'Karakum Desert',
      answer: 'Antarctic Desert',
    ),
    QuizQuestion(
      question: 'What year did the Titanic sink?',
      option1: '1905',
      option2: '1912',
      option3: '1915',
      option4: '1923',
      answer: '1912',
    ),
    QuizQuestion(
      question: 'Which country is known as the Land of the Rising Sun?',
      option1: 'China',
      option2: 'Japan',
      option3: 'South Korea',
      option4: 'Thailand',
      answer: 'Japan',
    ),
    QuizQuestion(
      question: 'Who is known as the Father of Modern Physics?',
      option1: 'Isaac Newton',
      option2: 'Niels Bohr',
      option3: 'Albert Einstein',
      option4: 'James Clerk Maxwell',
      answer: 'Albert Einstein',
    ),
    QuizQuestion(
      question: 'What is the hardest natural substance on Earth?',
      option1: 'Gold',
      option2: 'Iron',
      option3: 'Diamond',
      option4: 'Platinum',
      answer: 'Diamond',
    ),
    QuizQuestion(
      question: 'What is the longest river in the world?',
      option1: 'Amazon River',
      option2: 'Nile River',
      option3: 'Yangtze River',
      option4: 'Mississippi River',
      answer: 'Amazon River',
    ),
    QuizQuestion(
      question: 'Who wrote "The Catcher in the Rye"?',
      option1: 'J.D. Salinger',
      option2: 'John Steinbeck',
      option3: 'Ernest Hemingway',
      option4: 'Ray Bradbury',
      answer: 'J.D. Salinger',
    ),
    QuizQuestion(
      question: 'What is the largest planet in our solar system?',
      option1: 'Earth',
      option2: 'Saturn',
      option3: 'Jupiter',
      option4: 'Neptune',
      answer: 'Jupiter',
    ),
    QuizQuestion(
      question: 'Which animal is known for its ability to change color?',
      option1: 'Chameleon',
      option2: 'Octopus',
      option3: 'Squid',
      option4: 'All of the above',
      answer: 'All of the above',
    ),
    QuizQuestion(
      question: 'What is the chemical symbol for Iron?',
      option1: 'Ir',
      option2: 'Fe',
      option3: 'I',
      option4: 'In',
      answer: 'Fe',
    ),
    QuizQuestion(
      question: 'Which planet is known as the "Morning Star" or "Evening Star"?',
      option1: 'Venus',
      option2: 'Mars',
      option3: 'Mercury',
      option4: 'Saturn',
      answer: 'Venus',
    ),
    QuizQuestion(
      question: 'What is the primary language spoken in Argentina?',
      option1: 'Spanish',
      option2: 'Portuguese',
      option3: 'Italian',
      option4: 'French',
      answer: 'Spanish',
    ),
    QuizQuestion(
      question: 'Who painted "The Last Supper"?',
      option1: 'Leonardo da Vinci',
      option2: 'Raphael',
      option3: 'Michelangelo',
      option4: 'Caravaggio',
      answer: 'Leonardo da Vinci',
    ),
    QuizQuestion(
      question: 'What is the main ingredient in guacamole?',
      option1: 'Tomato',
      option2: 'Avocado',
      option3: 'Pepper',
      option4: 'Onion',
      answer: 'Avocado',
    ),
    QuizQuestion(
      question: 'Which planet has the most moons?',
      option1: 'Earth',
      option2: 'Mars',
      option3: 'Saturn',
      option4: 'Jupiter',
      answer: 'Saturn',
    ),
    QuizQuestion(
      question: 'What is the smallest country in the world?',
      option1: 'Monaco',
      option2: 'San Marino',
      option3: 'Vatican City',
      option4: 'Liechtenstein',
      answer: 'Vatican City',
    ),
 QuizQuestion(
      question: 'What is the primary gas found in the Earth\'s atmosphere?',
      option1: 'Oxygen',
      option2: 'Carbon Dioxide',
      option3: 'Nitrogen',
      option4: 'Argon',
      answer: 'Nitrogen',
    ),
    QuizQuestion(
      question: 'Who is known as the "Father of the Computer"?',
      option1: 'Charles Babbage',
      option2: 'Alan Turing',
      option3: 'John von Neumann',
      option4: 'Ada Lovelace',
      answer: 'Charles Babbage',
    ),
    QuizQuestion(
      question: 'What is the largest organ in the human body?',
      option1: 'Heart',
      option2: 'Liver',
      option3: 'Skin',
      option4: 'Lung',
      answer: 'Skin',
    ),
    QuizQuestion(
      question: 'What is the smallest planet in our solar system?',
      option1: 'Mars',
      option2: 'Venus',
      option3: 'Mercury',
      option4: 'Earth',
      answer: 'Mercury',
    ),
    QuizQuestion(
      question: 'Who painted "The Persistence of Memory"?',
      option1: 'Salvador Dalí',
      option2: 'Pablo Picasso',
      option3: 'Claude Monet',
      option4: 'Vincent van Gogh',
      answer: 'Salvador Dalí',
    ),
    QuizQuestion(
      question: 'Which country is known as the "Land of the Midnight Sun"?',
      option1: 'Sweden',
      option2: 'Norway',
      option3: 'Finland',
      option4: 'Iceland',
      answer: 'Norway',
    ),
    QuizQuestion(
      question: 'What is the capital city of Japan?',
      option1: 'Osaka',
      option2: 'Kyoto',
      option3: 'Tokyo',
      option4: 'Hiroshima',
      answer: 'Tokyo',
    ),
    QuizQuestion(
      question: 'Who wrote "Moby Dick"?',
      option1: 'Herman Melville',
      option2: 'Mark Twain',
      option3: 'Nathaniel Hawthorne',
      option4: 'Charles Dickens',
      answer: 'Herman Melville',
    ),
    QuizQuestion(
      question: 'What is the hardest natural substance on Earth?',
      option1: 'Iron',
      option2: 'Gold',
      option3: 'Diamond',
      option4: 'Platinum',
      answer: 'Diamond',
    ),
    QuizQuestion(
      question: 'What is the main ingredient in traditional Japanese sushi?',
      option1: 'Rice',
      option2: 'Fish',
      option3: 'Seaweed',
      option4: 'Vegetables',
      answer: 'Rice',
    ),
    QuizQuestion(
      question: 'What is the longest river in Africa?',
      option1: 'Nile River',
      option2: 'Congo River',
      option3: 'Zambezi River',
      option4: 'Niger River',
      answer: 'Nile River',
    ),
    QuizQuestion(
      question: 'Who invented the telephone?',
      option1: 'Alexander Graham Bell',
      option2: 'Thomas Edison',
      option3: 'Nikola Tesla',
      option4: 'Samuel Morse',
      answer: 'Alexander Graham Bell',
    ),
    QuizQuestion(
      question: 'Which element has the symbol "Na"?',
      option1: 'Sodium',
      option2: 'Neon',
      option3: 'Nitrogen',
      option4: 'Nickel',
      answer: 'Sodium',
    ),
    QuizQuestion(
      question: 'What is the capital of South Africa?',
      option1: 'Cape Town',
      option2: 'Johannesburg',
      option3: 'Pretoria',
      option4: 'Durban',
      answer: 'Pretoria',
    ),
    QuizQuestion(
      question: 'What is the smallest planet in our solar system?',
      option1: 'Mercury',
      option2: 'Mars',
      option3: 'Venus',
      option4: 'Earth',
      answer: 'Mercury',
    ),
    QuizQuestion(
      question: 'Who wrote "Pride and Prejudice"?',
      option1: 'Jane Austen',
      option2: 'Charlotte Brontë',
      option3: 'Mary Shelley',
      option4: 'Emily Dickinson',
      answer: 'Jane Austen',
    ),
    QuizQuestion(
      question: 'Which planet is known as the "Red Planet"?',
      option1: 'Venus',
      option2: 'Mars',
      option3: 'Jupiter',
      option4: 'Saturn',
      answer: 'Mars',
    ),
    QuizQuestion(
      question: 'What is the main ingredient in a traditional Margherita pizza?',
      option1: 'Pepperoni',
      option2: 'Tomato',
      option3: 'Mozzarella',
      option4: 'Basil',
      answer: 'Tomato, mozzarella, basil and olive oil',
    ),
    QuizQuestion(
      question: 'Who is the author of "The Catcher in the Rye"?',
      option1: 'J.D. Salinger',
      option2: 'John Steinbeck',
      option3: 'Ernest Hemingway',
      option4: 'Ray Bradbury',
      answer: 'J.D. Salinger',
    ),
    QuizQuestion(
      question: 'What year did World War II end?',
      option1: '1941',
      option2: '1945',
      option3: '1948',
      option4: '1950',
      answer: '1945',
    ),

];
